JobPortal.Web/Controllers/CompanyController.cs
using JobPortal.Data;
using JobPortal.Data.Models;
using JobPortal.Services.Data.Interfaces;
using JobPortal.Web.Infrastructures.Extensions;
using JobPortal.Web.ViewModels.Company;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Claims;

using static JobPortal.Common.NotificationMessageConstants;

namespace JobPortal.Web.Controllers
{
    public class CompanyController : BaseController
    {

        private readonly ICompanyService companyService;
        private readonly IApplicantService applicantService;


        public CompanyController(ICompanyService _companyService, IApplicantService _applicantService)
        {
            this.companyService = _companyService;
          
            this.applicantService = _applicantService;
        }

        /// <summary>
        /// Add Company entity. User becomes Company
        /// </summary>
        /// <returns></returns>


        [HttpGet]
        public async Task<IActionResult> Become()
        {
            string? userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            

            bool IsCompany = await this.companyService.CompanyExistsByUserId(userId);
            bool IsApplicant = await this.applicantService.ApplicantExistsByUserId(userId);

            if (IsCompany)
            {
                this.TempData[ErrorMessage] = "You are already a recruiter!";

                return RedirectToAction("Index", "Home");
            }
            if (IsApplicant && !this.User.IsAdmin())
            {
                this.TempData[ErrorMessage] = "Applicant cannot become a recruiter!";

                return RedirectToAction("Index", "Home");
            }



            return View();
        }

        [HttpPost]
        public  async Task<IActionResult> Become(BecomeRecruiterFormModel model)
        {
            string? userId = User.FindFirstValue(ClaimTypes.NameIdentifier);


            bool IsCompany = await this.companyService.CompanyExistsByUserId(userId);
            bool IsApplicant = await this.applicantService.ApplicantExistsByUserId(userId);

            if (IsCompany)
            {
                this.TempData[ErrorMessage] = "You are already a recruiter!";

                return RedirectToAction("Index", "Home");
            }
            if (IsApplicant && !this.User.IsAdmin())
            {
                this.TempData[ErrorMessage] = "Applicant cannot become a recruiter!";

                return RedirectToAction("Index", "Home");
            }

            bool isPhoneNumberTaken = await this.companyService.CompanyExistsByPhoneNumber(model.Phone);

            if (isPhoneNumberTaken)
            {
                this.TempData[ErrorMessage] = "Company with the provided phone number already exists!";
                this.ModelState.AddModelError(nameof(model.Phone), "Company with the provided phone number already exists!");
                return View(model);

            }

            if (!ModelState.IsValid)
            {
                
                return View(model);
            }

            try
            {


                await companyService.Create(model, userId);
                this.TempData[SuccessMessage] = "Successfull registration as a recruiter!";

               

            }
            catch (Exception)
            {
                this.TempData[ErrorMessage] = "Unexpected error occurred while registering you as an recruiter! Please try again later or contact administrator!";
                return RedirectToAction("Index", "Home");


            }



            return RedirectToAction("Index", "Home");
        }



    }
}

JobPortal.Web/Controllers/JobOfferController.cs
using JobPortal.Data.Models;
using JobPortal.Services.Data;
using JobPortal.Services.Data.Interfaces;
using JobPortal.Web.Infrastructures.Extensions;
using JobPortal.Web.ViewModels.Applicant;
using JobPortal.Web.ViewModels.JobOffer;
using JopPortal.Services.Data.Models.JobOffer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

using static JobPortal.Common.NotificationMessageConstants;

namespace JobPortal.Web.Controllers
{
    public class JobOfferController : BaseController
    {
        private readonly ICompanyService companyService;
        private readonly IJobOfferService jobOfferService;
        private readonly IApplicantService applicantService;
        private readonly ISelectOptionCollectionService selectOptionCollectionService;


        public JobOfferController(ICompanyService _companyService, IJobOfferService _jobOfferService, ISelectOptionCollectionService _selectOptionCollectionService, IApplicantService _applicantService)
        {
            this.companyService = _companyService;
            this.jobOfferService = _jobOfferService;
            this.applicantService = _applicantService;
            this.selectOptionCollectionService = _selectOptionCollectionService;


        }

        /// <summary>
        /// Get All Job Offers filtered and paged
        /// </summary>
        /// <param name="queryModel"></param>
        /// <returns></returns>


        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> All([FromQuery]AllJobOffersQueryModel queryModel)
        {
            string? userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            bool IsCompanay = await this.companyService.CompanyExistsByUserId(userId);
            bool IsApplicant = await this.applicantService.ApplicantExistsByUserId(userId);

            if (!IsCompanay && !IsApplicant)
            {
                this.TempData[ErrorMessage] = "Access denied! You have to be a recruiter or applicant!";

                return RedirectToAction("Index", "Home");

            }

            try
            {
                AllJobOffersFilteredAndPagedServiceModel serviceModel =
               await this.jobOfferService.All(queryModel);

                queryModel.JobOffers = serviceModel.JobOffers;
                queryModel.TotalJobOffers = serviceModel.TotalJobOffersCount;
                queryModel.JobTypes = await selectOptionCollectionService.GetJobTypes();
                queryModel.Levels = await selectOptionCollectionService.GetLevels();
                queryModel.Towns = await selectOptionCollectionService.GetTowns();
                queryModel.ProgrammingLanguages = await selectOptionCollectionService.GetProgrammingLanguages();
               
            }
            catch (Exception)
            {

                this.TempData[ErrorMessage] = "Unexpected error occurred! Please try again later or contact administrator!";
                return RedirectToAction("Index", "Home");
            }

            return View(queryModel);

        }


        /// <summary>
        /// Add Job Offer to CompanyJobOffers
        /// </summary>
        /// <returns></returns>

        [HttpGet]
        public async Task<IActionResult> Add()
        {

            string? userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            bool IsCompanay = await this.companyService.CompanyExistsByUserId(userId);


            if (!IsCompanay)
            {
                this.TempData[ErrorMessage] = "Access denied! You have to be a recruiter!";

                return RedirectToAction("Index", "Home");
            }



            JobOfferAddFormViewModel model = new JobOfferAddFormViewModel()
            {
                Towns = await selectOptionCollectionService.GetTowns(),
                ProgrammingLanguages = await selectOptionCollectionService.GetProgrammingLanguages(),
                Levels = await selectOptionCollectionService.GetLevels(),
                JobTypes = await selectOptionCollectionService.GetJobTypes(),
            };


            return View(model);

        }


        [HttpPost]
        public async Task<IActionResult> Add(JobOfferAddFormViewModel model)
        {
            string? userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            bool IsCompanay = await this.companyService.CompanyExistsByUserId(userId);

            if (!IsCompanay)
            {
                this.TempData[ErrorMessage] = "Access denied! You have to be a recruiter!";

                return RedirectToAction("Index", "Home");
            }
           


            if (!ModelState.IsValid)
            {
                model.Towns = await selectOptionCollectionService.GetTowns();
                model.ProgrammingLanguages = await selectOptionCollectionService.GetProgrammingLanguages();
                model.Levels = await selectOptionCollectionService.GetLevels();
                model.JobTypes = await selectOptionCollectionService.GetJobTypes();

                return View(model);
            }

            try
            {

               
                await jobOfferService.AddJobOffer(model, userId);
                this.TempData[SuccessMessage] = "Job offer successfully added!";

               

            }
            catch (Exception)
            {
                this.TempData[ErrorMessage] = "Unexpected error occurred while adding new job offer! Please try again later or contact administrator!";
                return RedirectToAction(nameof(All));


            }



            return RedirectToAction(nameof(JobOffersPublishedFromACompany));
        }

        /// <summary>
        /// Get all Job Offers Published by Company!
        /// </summary>
        /// <returns></returns>


        [HttpGet]
        public async Task<IActionResult> JobOffersPublishedFromACompany()
        {
            List<JobOfferAllViewModel> companyJobOffers = new List<JobOfferAllViewModel>();
            string? userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            bool IsCompanay = await this.companyService.CompanyExistsByUserId(userId);

            if (!IsCompanay)
            {
                this.TempData[ErrorMessage] = "Access denied! You have to be a recruiter!";

                return RedirectToAction(nameof(All));
            }

            try
            {
                companyJobOffers.AddRange(await jobOfferService.AllByCompanyId(userId!));
            }
            catch (Exception)
            {
                this.TempData[ErrorMessage] = "Unexpected error occurred! Please try again later or contact administrator!";
                return RedirectToAction(nameof(All));
                
            }

            

            return this.View(companyJobOffers);


        }




        /// <summary>
        /// Get all Job Offers Applied from Applicant!
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>

        [HttpGet]
        public async Task<IActionResult> JobOffersAppliedFromAnApplicant(string id)
        {
            List<JobOfferAllViewModel> applicantJobOffers = new List<JobOfferAllViewModel>();
            string? userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var applicant = await applicantService.GetApplicantById(userId);


            bool IsApplicant = await this.applicantService.ApplicantExistsByUserId(userId);

            bool IsCompanay = await this.companyService.CompanyExistsByUserId(userId);

            if (!IsCompanay && !IsApplicant)
            {
                this.TempData[ErrorMessage] = "Access denied! You have to be a recruiter or an applicant!";

                return RedirectToAction(nameof(All));
            }

            try
            {
                applicantJobOffers.AddRange(await jobOfferService.AllByApplicantId(id!));
            }
            catch (Exception)
            {
                this.TempData[ErrorMessage] = "Unexpected error occurred! Please try again later or contact administrator!";
                return RedirectToAction(nameof(All));

            }



            return this.View(applicantJobOffers);


        }

        /// <summary>
        /// Get Details of Job Offer
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>


        [HttpGet]
        public async Task<IActionResult> Details(string id)
        {
            string? userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            bool IsCompanay = await this.companyService.CompanyExistsByUserId(userId);
            bool IsApplicant = await this.applicantService.ApplicantExistsByUserId(userId);

            if (!IsCompanay && !IsApplicant)
            {
                this.TempData[ErrorMessage] = "Access denied! You have to be a recruiter or applicant!";

                return RedirectToAction("Index", "Home");

            }


            var jobOffer = await jobOfferService.GetJobOfferById(id);

            if (jobOffer == null)
            {
                this.TempData[ErrorMessage] = "Job Offer with the provided id does not exist!";
                return RedirectToAction(nameof(All));

            }


            try
            {
                JobOfferDetailsViewModel model = await jobOfferService.GetDetailsOfJobOffer(jobOffer, id);
                return View(model);

            }
            catch (Exception)
            {
                this.TempData[ErrorMessage] = "Unexpected error occurred! Please try again later or contact administrator!";
                return RedirectToAction(nameof(All));

            }


        }

        /// <summary>
        /// Set IsDelete property of Job Offer to true
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {

JobPortal.Web/Views/Shared/_ApplicantPartial.cshtml
@model ApplicantAllViewModel
<div class="col-md-4">
    <div class="card mb-3">
        <div class="card-body text-center bg-secondary text-white">
            <img src="@Model.ImageUrl" class="rounded mx-auto d-block" />
            <h4>@Model.FirstName @Model.LastName</h4>
            
            <h6>
                Town:
                <b>@Model.Town</b>
            </h6>
            <h6>
                Level:
                <b>@Model.Level</b>
            </h6>
            <h6>
                Programming Language:
                <b>@Model.ProgrammingLanguage</b>
            </h6>
           
            <br />
            <a asp-controller="Applicant" asp-action="Details" asp-route-id="@Model.Id"
               class="btn btn-success">Details</a>
            

          
        </div>
    </div>
</div>

JobPortal.Web/Views/Shared/_JobOfferPartial.cshtml
@model JobOfferAllViewModel
<div class="col-md-4">
    <div class="card mb-3">
       <div class="card-body text-center bg-secondary text-white">
            <img src="@Model.CompanyImageUrl" class="rounded mx-auto d-block" />
            <h4>@Model.Name</h4>
           
            <h6>
                Town:
                <b>@Model.Town</b>
            </h6>
            <h6>Level:
                <b>@Model.Level</b>
            </h6>
            <h6>Programming Language:
                <b>@Model.ProgrammingLanguage</b>
           </h6>
            <h6>Job Type:
                <b>@Model.JobType</b>
           </h6>
            <h6>
                Published:
                <b>@Model.CreatedOn</b>
            </h6>
            <h6>
                Company Name:
                <b>@Model.Company</b>
            </h6>
            <h6>
               Applicants:
                <b>@Model.JobOfferApplicantsCount</b>
            </h6>
            <br />
            <a asp-controller="JobOffer" asp-action="Details" asp-route-id="@Model.Id"
               class="btn btn-success">Details</a>
       
        </div>
    </div>
</div>

JobPortal.Web/Views/Shared/_Layout.cshtml
@using System.Security.Claims;
@using JobPortal.Web.Infrastructures.Extensions;
@inject JobPortal.Services.Data.Interfaces.ICompanyService companyService;
@inject JobPortal.Services.Data.Interfaces.IApplicantService applicantService;



<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Best IT Job Offers</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/JobPortal.Web.styles.css" asp-append-version="true" />

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js" integrity="sha512-lbwH47l/tPXJYG9AcFNoJaTMhGvYWhVM9YI43CT+uteTRRaiLCui8snIgyAN8XWgNjNhCqlAUdzZptso6OCoFQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.css" integrity="sha512-6S2HWzVFxruDlZxI3sXOZZ4/eJ8AcxkQH1+JjSe/ONCEqR9L4Ysq5JdT5ipqtzU7WHalNwzwBv+iE51gNHJNqQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    
</head>
<body>
    <partial name="_NotificationsPartial"/>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container-fluid">
               <img src="/img/icons8-hired-64.png"/>
                <a class="navbar-brand text-primary text-xl-start" asp-area="" asp-controller="Home" asp-action="Index">Job.IT Portal - Seek or Offer</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @{
                            string? userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
                            bool IsCompany = await companyService.CompanyExistsByUserId(userId);
                            bool isApplicant = await applicantService.ApplicantExistsByUserId(userId);
                            if ((User?.Identity?.IsAuthenticated ?? false) && User.IsAdmin())
                            {
                                
                            }
                            else if ((User?.Identity?.IsAuthenticated ?? false) && isApplicant)
                            {
                                var applicant = await applicantService.GetApplicantByApplicationUserId(userId);


                                <li class="nav-item">
                                    @*applicant/company*@
                                    <a class="nav-link text-white" asp-area="" asp-controller="JobOffer" asp-action="All">All Job Offers</a>
                                </li>
                               
                                <li class="nav-item">
                                    @*applicant*@

                                    <a class="nav-link text-white" asp-area="" asp-controller="JobOffer" asp-action="JobOffersAppliedFromAnApplicant" asp-route-id="@applicant.Id">My Job Offers</a>
                                </li>


                            }
                            else if ((User?.Identity?.IsAuthenticated ?? false) && IsCompany)
                            {
                                <li class="nav-item">
                                    @*applicant/company*@
                                    <a class="nav-link text-white" asp-area="" asp-controller="JobOffer" asp-action="All">All Job Offers</a>
                                </li>
                                <li class="nav-item">
                                    @*company*@
                                    <a class="nav-link text-white" asp-area="" asp-controller="Applicant" asp-action="All">All Applicants</a>
                                </li>
                                <li class="nav-item">
                                    @*company*@
                                    <a class="nav-link text-white" asp-area="" asp-controller="JobOffer" asp-action="JobOffersPublishedFromACompany">My Job Offers Published</a>
                                </li>
                                <li class="nav-item">
                                    @*company*@
                                    <a class="nav-link text-white" asp-area="" asp-controller="JobOffer" asp-action="Add">Add Job Offer</a>
                                </li>


                            }
                            else if ((User?.Identity?.IsAuthenticated ?? false) &&  (!User.IsAdmin()))
                            {

                                <li class="nav-item">
                                    @*applicationUser*@
                                    <a class="nav-link text-white" asp-area="" asp-controller="Company" asp-action="Become">Become Recruiter</a>
                                </li>
                                <li class="nav-item">
                                    @*applicationUser*@
                                    <a class="nav-link text-white" asp-area="" asp-controller="Applicant" asp-action="Become">Become Applicant</a>
                                </li>

                            }
                           

                        }

                       
 
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="text-center text-white border-top footer text-muted" style="background-color: #caced1;">
        <!-- Grid container -->
        <div class="container p-4">
            <!-- Section: Images -->
            <section class="">
                <div class="row">
                    <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
                        <div class="bg-image hover-overlay ripple shadow-1-strong rounded"
                             data-ripple-color="light">
                            <img src="~/img/topEmlpoyers/SoftUni.png"
                                 class="w-100" />
                            <a href="#!">
                                <div class="mask"
                                     style="background-color: rgba(251, 251, 251, 0.2);"></div>
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
                        <div class="bg-image hover-overlay ripple shadow-1-strong rounded"
                             data-ripple-color="light">
                            <img src="~/img/topEmlpoyers/dxc.png"
                                 class="w-100" />
                            <a href="#!">
                                <div class="mask"
                                     style="background-color: rgba(251, 251, 251, 0.2);"></div>
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
                        <div class="bg-image hover-overlay ripple shadow-1-strong rounded"
                             data-ripple-color="light">
                            <img src="~/img/topEmlpoyers/Indeavr.jpg"
                                 class="w-100" />
                            <a href="#!">
                                <div class="mask"
                                     style="background-color: rgba(251, 251, 251, 0.2);"></div>
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
                        <div class="bg-image hover-overlay ripple shadow-1-strong rounded"
                             data-ripple-color="light">
                            <img src="~/img/topEmlpoyers/SmartIT.jpg"
                                 class="w-100" />
                            <a href="#!">
                                <div class="mask"
                                     style="background-color: rgba(251, 251, 251, 0.2);"></div>
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
                        <div class="bg-image hover-overlay ripple shadow-1-strong rounded"
                             data-ripple-color="light">
                            <img src="/img/topEmlpoyers/Bosch.png"
                                 class="w-100" />
                            <a href="#!">
                                <div class="mask"
                                     style="background-color: rgba(251, 251, 251, 0.2);"></div>
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
                        <div class="bg-image hover-overlay ripple shadow-1-strong rounded"
                             data-ripple-color="light">
                            <img src="~/img/topEmlpoyers/CocaCola.png"
                                 class="w-100" />
                            <a href="#!">
                                <div class="mask"
                                     style="background-color: rgba(251, 251, 251, 0.2);"></div>
                            </a>
                        </div>
                    </div>
                </div>
            </section>
            <!-- Section: Images -->
        </div>
        <!-- Grid container -->
        <!-- Copyright -->
        <div class="text-center p-3" >
            © @DateTime.UtcNow.Date.Year - Job.IT.Portal
        </div>
       
    </footer>

    
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

JobPortal.Web/Views/Shared/_NotificationsPartial.cshtml
@using static JobPortal.Common.NotificationMessageConstants

@if (TempData.ContainsKey(ErrorMessage))
{
    <script>toastr.error('@TempData[ErrorMessage]')</script>

}
@if (TempData.ContainsKey(WarningMessage))
{
    <script>toastr.warning('@TempData[WarningMessage]')</script>

}@if (TempData.ContainsKey(SuccessMessage))
{
    <script>toastr.success('@TempData[SuccessMessage]')</script>

}@if (TempData.ContainsKey(InformationMessage))
{
    <script>toastr.info('@TempData[InformationMessage]')</script>

}