JobPortal.Web/Controllers/ApplicantController.cs
using JobPortal.Data.Models;
using JobPortal.Services.Data;
using JobPortal.Services.Data.Interfaces;
using JobPortal.Web.Infrastructures.Extensions;
using JobPortal.Web.ViewModels.Applicant;
using JobPortal.Web.ViewModels.Company;
using JobPortal.Web.ViewModels.JobOffer;
using JopPortal.Services.Data.Models.Applicant;
using JopPortal.Services.Data.Models.JobOffer;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

using static JobPortal.Common.NotificationMessageConstants;

namespace JobPortal.Web.Controllers
{
    public class ApplicantController : BaseController
    {
        private readonly IApplicantService applicantService;
        private readonly ICompanyService companyService;
        private readonly ISelectOptionCollectionService selectOptionCollectionService;
        private readonly IJobOfferService jobOfferService;

        public ApplicantController(IApplicantService _applicantService, ICompanyService _companyService, ISelectOptionCollectionService _selectOptionCollectionService, IJobOfferService _jobOfferService)
        {
            this.applicantService = _applicantService;
            this.companyService= _companyService;
           
            this.selectOptionCollectionService = _selectOptionCollectionService;
            this.jobOfferService = _jobOfferService;
        }

        /// <summary>
        /// User becomes Applicant!
        /// Add Applicant entity!
        /// </summary>
        /// <returns></returns>


        [HttpGet]
        public async Task<IActionResult> Become()
        {
            string? userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            bool IsApplicant = await this.applicantService.ApplicantExistsByUserId(userId);
            bool IsCompany = await this.companyService.CompanyExistsByUserId(userId);


            if (IsApplicant)
            {
                this.TempData[ErrorMessage] = "You are already an applicant!";

                return RedirectToAction("Index", "Home");
            }
            if (IsCompany && !User.IsAdmin())
            {
                this.TempData[ErrorMessage] = "Recruiter cannot become an applicant!";

                return RedirectToAction("Index", "Home");
            }

            BecomeApplicantFormModel model = new BecomeApplicantFormModel()
            {
                Towns = await selectOptionCollectionService.GetTowns(),
                ProgrammingLanguages = await selectOptionCollectionService.GetProgrammingLanguages(),
                Levels = await selectOptionCollectionService.GetLevels()
            };


            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Become(BecomeApplicantFormModel model)
        {
            string? userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            bool IsApplicant = await this.applicantService.ApplicantExistsByUserId(userId);
            bool IsCompany = await this.companyService.CompanyExistsByUserId(userId);


            if (IsApplicant)
            {
                this.TempData[ErrorMessage] = "You are already an applicant!";

                return RedirectToAction("Index", "Home");
            }
            if (IsCompany && !User.IsAdmin())
            {
                this.TempData[ErrorMessage] = "Recruiter cannot become an applicant!";

                return RedirectToAction("Index", "Home");
            }


            bool isPhoneNumberTaken = await this.applicantService.ApplicantExistsByPhoneNumber(model.Phone);

            if (isPhoneNumberTaken)
            {
                this.TempData[ErrorMessage] = "Applicant with the provided phone number already exists!";
                this.ModelState.AddModelError(nameof(model.Phone), "Applicant with the provided phone number already exists!");
                model.Towns = await selectOptionCollectionService.GetTowns();
                model.ProgrammingLanguages = await selectOptionCollectionService.GetProgrammingLanguages();
                model.Levels = await selectOptionCollectionService.GetLevels();
                return View(model);

            }

            if (!ModelState.IsValid)
            {
                model.Towns = await selectOptionCollectionService.GetTowns();
                model.ProgrammingLanguages = await selectOptionCollectionService.GetProgrammingLanguages();
                model.Levels = await selectOptionCollectionService.GetLevels();
                return View(model);
            }

            try
            {


                await applicantService.Create(model, userId);
                this.TempData[SuccessMessage] = "Successfull registration as an applicant!";


            }
            catch (Exception)
            {
                this.TempData[ErrorMessage] = "Unexpected error occurred while registering you as an applicant! Please try again later or contact administrator!";
                return RedirectToAction("Index", "Home");


            }



            return RedirectToAction("Index", "Home");
        }


        /// <summary>
        /// Get All Applicants filtered and paged
        /// </summary>
        /// <param name="queryModel"></param>
        /// <returns></returns>

        [HttpGet]
        public async Task<IActionResult> All([FromQuery] AllApplicantsQueryModel queryModel)
        {

            string? userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            bool IsCompanay = await this.companyService.CompanyExistsByUserId(userId);
            

            if (!IsCompanay)
            {
                this.TempData[ErrorMessage] = "Access denied! You have to be a recruiter!";

                return RedirectToAction("Index", "Home");

            }

            try
            {
                AllApplicantsFilteredAndPagedServiceModel serviceModel =
               await this.applicantService.All(queryModel);

                queryModel.Applicants = serviceModel.Applicants;
                queryModel.TotalApplicants = serviceModel.TotalApplicantsCount;
                queryModel.Levels = await selectOptionCollectionService.GetLevels();
                queryModel.Towns = await selectOptionCollectionService.GetTowns();
                queryModel.ProgrammingLanguages = await selectOptionCollectionService.GetProgrammingLanguages();

            }
            catch (Exception)
            {

                this.TempData[ErrorMessage] = "Unexpected error occurred! Please try again later or contact administrator!";
                return RedirectToAction("Index", "Home");
            }

            return View(queryModel);


        }


        [HttpGet]
        public async Task<IActionResult> ApplicantsAppliedForJobOffer(string id)
        {
            List<ApplicantAllViewModel> applicantsAppliedForJob = new List<ApplicantAllViewModel>();
            string? userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var joboffer = await jobOfferService.GetJobOfferById(id);
           
            bool IsCompanay = await this.companyService.CompanyExistsByUserId(userId);

            if (!IsCompanay && !User.IsAdmin())
            {
                this.TempData[ErrorMessage] = "Access denied! You have to be a recruiter!";

                return RedirectToAction(nameof(All));
            }
            try
            {
                applicantsAppliedForJob.AddRange(await applicantService.AllByJobOfferId(id!));
            }
            catch (Exception)
            {
                this.TempData[ErrorMessage] = "Unexpected error occurred! Please try again later or contact administrator!";
                return RedirectToAction(nameof(All));

            }



            return this.View(applicantsAppliedForJob);


        }





        /// <summary>
        /// Get Details of Applicant by Id
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>

        public async Task <IActionResult> Details(string id)
        {
            string? userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            bool IsCompanay = await this.companyService.CompanyExistsByUserId(userId);

            if (!IsCompanay)
            {
                this.TempData[ErrorMessage] = "Access denied! You have to be a recruiter!";

                return RedirectToAction("Index", "Home");
            }


            var applicant = await applicantService.GetApplicantById(id);

            if (applicant == null)
            {
                this.TempData[ErrorMessage] = "Applicant with the provided id does not exist!";
                return RedirectToAction(nameof(All));

            }


            try
            {
                ApplicantDetailsViewModel model = await applicantService.GetDetailsOfApplicant(applicant, id);
                return View(model);

            }
            catch (Exception)
            {
                this.TempData[ErrorMessage] = "Unexpected error occurred! Please try again later or contact administrator!";
                return RedirectToAction(nameof(All));

            }



        }

      
    }
}

JobPortal.Web/Views/Applicant/All.cshtml
@model AllApplicantsQueryModel

@{
    ViewBag.Title = "All Applicants";
}
<h2 class="text-center">@ViewBag.Title</h2>
<hr />

<link rel="stylesheet" href="~/css/All.css" asp-append-version="true" />


<form method="get">
    <div class="row">
        
        <div class="form-group col-md-3 d-flex justify-content-between">
            <div class="form-group">
                <label asp-for="Level"></label>
                <select asp-for="Level" class="form-control">
                    <option value="">All</option>
                    @foreach (var level in Model.Levels)
                    {
                        <option value="@level.Name">@level.Name</option>
                    }
                </select>
            </div>
        </div>
        <div class="form-group col-md-3 d-flex justify-content-between">
            <div class="form-group">
                <label asp-for="Town"></label>
                <select asp-for="Town" class="form-control">
                    <option value="">All</option>
                    @foreach (var town in Model.Towns)
                    {
                        <option value="@town.Name">@town.Name</option>
                    }
                </select>
            </div>
        </div>
        <div class="form-group col-md-3 d-flex justify-content-between">
            <div class="form-group">
                <label asp-for="ProgrammingLanguage"></label>
                <select asp-for="ProgrammingLanguage" class="form-control">
                    <option value="">All</option>
                    @foreach (var programmingLanguage in Model.ProgrammingLanguages)
                    {
                        <option value="@programmingLanguage.Name">@programmingLanguage.Name</option>
                    }
                </select>
            </div>
        </div>
        <div class="form-group col-md-3">
            <label asp-for="SearchString"></label>
            <input asp-for="SearchString" class="form-control" placeholder="...">
        </div>
        
        <div class="container d-flex align-items-center justify-content-center">
            <div class="form-group mt-4 p-2">
                <input type="submit" value="Search" class="btn btn-primary" />
            </div>
        </div>
    </div>
</form>
@{
    int previousPage = Model.CurrentPage - 1;
    if (previousPage < 1)
    {
        previousPage = 1;
    }
    int maxPage = (int)Math.Ceiling((double)Model.TotalApplicants /
    Model.ApplicantsPerPage);

}

<div class="row mb-5">
    <div class="col-md-6 d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-primary @(Model.CurrentPage == 1 ? "disabled" : string.Empty)"
           asp-controller="Applicant"
           asp-action="All"
           asp-route-currentPage="@previousPage"
           
           asp-route-level="@Model.Level"
           asp-route-town="@Model.Town"
           asp-route-programmingLanguage="@Model.ProgrammingLanguage"
           asp-route-searchString="@Model.SearchString"><<</a>
    </div>
    @{
        bool shouldNextPageBeDisabled = Model.CurrentPage == maxPage ||
        !Model.Applicants.Any();
    }
    <div class="col-md-6 d-grid gap-2 d-md-flex justify-content-md-end">
        <a class="btn btn-primary
@(shouldNextPageBeDisabled ? "disabled" : string.Empty)"
           asp-controller="Applicant"
           asp-action="All"
           asp-route-currentPage="@(Model.CurrentPage + 1)"
           asp-route-level="@Model.Level"
           asp-route-town="@Model.Town"
           asp-route-programmingLanguage="@Model.ProgrammingLanguage"
           asp-route-searchString="@Model.SearchString">>></a>
    </div>
</div>
@if (!Model.Applicants.Any())
{
    <h2 class="text-center">No Applicants found by the given criteria!</h2>
}
<div class="row">
    @foreach (var applicant in Model.Applicants)
    {
        <partial name="_ApplicantPartial" model="@applicant" />
    }
</div>

JobPortal.Web/Views/Applicant/ApplicantsAppliedForJobOffer.cshtml
@using System.Security.Claims;
@using JobPortal.Web.Infrastructures.Extensions;
@inject JobPortal.Services.Data.Interfaces.ICompanyService companyService;


@model List<ApplicantAllViewModel>
@{
    ViewBag.Title = "All applicants have applied for the job";
    string? userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);

}

<link rel="stylesheet" href="~/css/companyJobOffers.css" asp-append-version="true" />


   
    
<h2 class="text-center">@ViewBag.Title</h2>
    



<hr />



@if (!Model.Any())
{

    <h2 class="text-center">The Job Offer does not have any applicant applied for!</h2>

}
else
{
    <div class="row">
        @foreach (ApplicantAllViewModel applicant in Model)
        {
            <partial name="_ApplicantPartial" model="applicant" />

        }
    </div>
}

JobPortal.Web/Views/Applicant/Become.cshtml
@model BecomeApplicantFormModel
@{
    ViewBag.Title = "Become Applicant";
}
<h2 class="text-center">@ViewBag.Title</h2>
<hr />


<link rel="stylesheet" href="~/css/becomeApplicant.css" asp-append-version="true" />



<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <!-- First Name input -->
            <div class="form-outline mb-sm-1">
                <input asp-for="@Model.FirstName" type="text" id="form4Example1" class="form-control" />
                <label asp-for="@Model.FirstName" class="form-label" for="form4Example1"></label>
                <span asp-validation-for="@Model.FirstName" class="small text-danger"></span>



            </div>
            <!-- Last Name input -->

            <div class="form-outline mb-sm-1">
                <input asp-for="@Model.LastName" type="text" id="form4Example1" class="form-control" />
                <label asp-for="@Model.LastName" class="form-label" for="form4Example1"></label>
                <span asp-validation-for="@Model.LastName" class="small text-danger"></span>

            </div>

            <!-- Img Url -->
            <div class="form-outline mb-sm-1">
                <input asp-for="@Model.ImgUrl" type="url" id="form4Example2" class="form-control" placeholder="https://" />
                <label asp-for="@Model.ImgUrl" class="form-label" for="form4Example2"></label>
                <span asp-validation-for="@Model.ImgUrl" class="small text-danger"></span>

            </div>
            <!-- Phone -->
            <div class="form-outline mb-sm-1">
                <input asp-for="@Model.Phone" type="tel" id="form4Example2" class="form-control" placeholder="+359888888888" />
                <label asp-for="@Model.Phone" class="form-label" for="form4Example2"></label>
                <span asp-validation-for="@Model.Phone" class="small text-danger"></span>

            </div>
            <!-- Town -->
            <div class="mb-sm-1">
                <select asp-for="@Model.TownId" class="form-control">
                    @foreach (var town in Model.Towns)
                    {
                        <option value="@town.Id">@town.Name</option>
                    }
                </select>
                <label asp-for="@Model.TownId" class="form-label"></label>

                <span asp-validation-for="@Model.TownId" class="text-danger"></span>
            </div>
            <!-- Level -->
            <div class="mb-sm-1">
                <select asp-for="@Model.LevelId" class="form-control">
                    @foreach (var level in Model.Levels)
                    {
                        <option value="@level.Id">@level.Name</option>
                    }
                </select>
                <label asp-for="@Model.LevelId" class="form-label"></label>
                <span asp-validation-for="@Model.LevelId" class="text-danger"></span>
            </div>
            <!-- Programming Language -->
            <div class="mb-sm-1">
                <select asp-for="@Model.ProgrammingLanguageId" class="form-control">
                    @foreach (var pl in Model.ProgrammingLanguages)
                    {
                        <option value="@pl.Id">@pl.Name</option>
                    }
                </select>
                <label asp-for="@Model.ProgrammingLanguageId" class="form-label"></label>

                <span asp-validation-for="@Model.ProgrammingLanguageId" class="text-danger"></span>
            </div>



            <!-- Submit button -->
            <button type="submit" asp-controller="Applicant" asp-action="Become" class="btn btn-primary btn-block mb-4">Send</button>
        </form>
    </div>

</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
    }

JobPortal.Web/Views/Applicant/Details.cshtml
@model ApplicantDetailsViewModel
@{
    ViewBag.Title = "Applicant Details";
}
<link rel="stylesheet" href="~/css/All.css" asp-append-version="true" />


<div class="container" style="display:inline">
    <div class="row">
        <div class="col-4">
            <img class="card-img-top" style="width: 20rem;"
                 src="@Model.ImageUrl" alt="Applicant Image">
        </div>
        <div class="card col-6 border-0 bg-secondary text-white">
            <p style="font-size:25px;"><u>@Model.FirstName @Model.LastName</u></p>
            <p>Applicant Phone: <b>@Model.Phone</b></p>
            <p>Applicant Email: <b>@Model.Email</b></p>
            <p>Applied for  <b>@Model.ApplicantJobOffersCount  Applications</b></p>
            
            <form class="input-group-sm" asp-route-id="@Model.Id" asp-controller="JobOffer" asp-action="JobOffersAppliedFromAnApplicant" method="get">
                <input type="submit" value="Applications" class="fs-6 btn btn-warning mb-3 p-2" />
            </form>

            
        </div>
        
    </div>
</div>